settings_version: 0.0.5
datasets_dir: D:\Escritorio\Proyectos\Konecto_Training_Model
weights_dir: weights
runs_dir: runs
uuid: aaffab7515e0d48074ec65af2deddf8168c36cc70f4a21adebd48d5f549ff30d
sync: true
api_key: ""
openai_api_key: ""
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
vscode_msg: true
